import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = [
  Category(
    id: 'c1',
    title: 'HALAL',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'SEA FOODS',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'VEGAN',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'KETO',
    color: Colors.amber,
  ),
];

// ignore: unnecessary_const
const DUMMY_MEALS = const [
  Meal(
      id: 'm1',
      categories: [
        'c1',
      ],
      title: 'Salmon Empanadas',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/salmon_empanadas.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/Salmon_Empanadas.glb?raw=true',
      details: 'Salmon Fillets, Pie Crust, Fresh Parsely and Fresh Basil',
      sauce:
          'Butter, Flour, dry mustard, salt, pepper, milk, shredded gruyere cheese',
      scale: 1.4,
      isHalal: true,
      isKeto: false,
      isSeaFood: false,
      isVegan: false,
      isDessert: false,
      isAllergyEgg: true,
      isAllergyMilk: true,
      isAllergyCheese: true,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "50.00",
      isFiftyBelow: true,
      isFiftyToOneHundred: true,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: false),
  Meal(
      id: 'm2',
      categories: [
        'c1',
        'c4',
      ],
      title: 'Roasted Chicken',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/roasted_chicken.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/roasted_chicken.glb?raw=true',
      details:
          'Whole Chicken(giblets removed), salt, pepper, onion powder, margarine, amd potato',
      sauce: '',
      scale: 0.2,
      isHalal: true,
      isKeto: true,
      isSeaFood: false,
      isDessert: false,
      isVegan: false,
      isAllergyEgg: false,
      isAllergyMilk: false,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      isFiftyBelow: false,
      isFiftyToOneHundred: false,
      isOneHundredToOneFifty: false,
      price: "175.00",
      isOneFiftyToTwoHundred: true,
      isTwoHundredAbove: true),
  Meal(
      id: 'm3',
      categories: [
        'c1',
      ],
      title: 'Chicken Meal',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/chicken_meal.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/Chicken_Meal.glb?raw=true',
      details: 'fried rice with egg, fried chicken, lemon, onion, and ketchup',
      sauce: '',
      scale: 1.2,
      isHalal: true,
      isKeto: false,
      isSeaFood: false,
      isDessert: false,
      isVegan: false,
      isAllergyEgg: true,
      isAllergyMilk: false,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "85.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: true,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: false),
  Meal(
      id: 'm4',
      categories: [
        'c1',
      ],
      title: 'Croissant Norweski',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/croissant_norweski.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/croissant_norweski.glb?raw=true',
      details: 'croissant, cocumber, tomato, bacon cheese, letuce, ',
      sauce: '',
      isHalal: true,
      isKeto: false,
      isSeaFood: false,
      isDessert: false,
      isVegan: false,
      isAllergyEgg: false,
      isAllergyMilk: false,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      scale: 0.1,
      isFiftyBelow: true,
      isFiftyToOneHundred: false,
      price: "175.00",
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: true,
      isTwoHundredAbove: false),
  Meal(
      id: 'm7',
      categories: [
        'c4',
      ],
      isHalal: false,
      isKeto: true,
      isSeaFood: false,
      isDessert: false,
      isVegan: false,
      title: 'Togsilog',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/TOSILOG.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/Tosilog.glb?raw=true',
      details:
          'Sinangag is garlic fried rice at the bottom. Next layer is the tocino (the cured pork belly). Top it off with a fried egg. Cucumber tomato relish on the side',
      sauce: '',
      scale: 0.7,
      isAllergyEgg: true,
      isAllergyMilk: false,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "65.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: true,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: false),
  Meal(
      id: 'm10',
      categories: ['c1', 'c3'],
      title: 'Vegie Bowl',
      imageUrl:
          'https://raw.githubusercontent.com/agnieve70/3dObjects/main/vegiebowl.png',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/vegiebowl.glb?raw=true',
      details: 'Carrots, broccoli, potato, green beans, corn',
      sauce: '',
      scale: 0.1,
      isHalal: true,
      isKeto: false,
      isSeaFood: false,
      isDessert: false,
      isVegan: true,
      isAllergyEgg: false,
      isAllergyMilk: false,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "48.00",
      isFiftyBelow: true,
      isFiftyToOneHundred: false,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: false),
  Meal(
      id: 'm13',
      categories: ['c1', 'c2'],
      title: 'Sashimi Plate',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/sashimi_plate.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/sashimi_plate.glb?raw=true',
      details: 'Strawberry, bread, fig, glaze',
      sauce: '',
      scale: 0.1,
      isHalal: true,
      isKeto: false,
      isSeaFood: true,
      isDessert: false,
      isVegan: false,
      isAllergyEgg: false,
      isAllergyMilk: false,
      isAllergyCheese: false,
      isAllergyFish: true,
      isAllergyShellFish: false,
      price: "88.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: true,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: false),
  Meal(
      id: 'm14',
      categories: ['c1', 'c2'],
      title: 'Unagi Bento',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/unagi_bento.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/unagi_bento.glb?raw=true',
      details: 'unagi(eel) Fillets, unagi sauce, steamed rice',
      sauce: '',
      scale: 1.4,
      isHalal: true,
      isKeto: false,
      isSeaFood: true,
      isDessert: false,
      isVegan: false,
      isAllergyEgg: false,
      isAllergyMilk: false,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: true,
      price: "99.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: true,
      isOneHundredToOneFifty: true,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: false),
  Meal(
      id: 'm15',
      categories: ['c1', 'c3'],
      title: 'Cinnamon Pastry',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/cinnamon.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/cinnamon.glb?raw=true',
      details:
          'Butter, Flour, Cream cheese, Baker’s yeast, Sugar, Egg, Powdered sugar, Brown sugar, Grounded cinnamon',
      sauce: '',
      scale: 0.11,
      isHalal: true,
      isKeto: false,
      isSeaFood: false,
      isDessert: false,
      isVegan: true,
      isAllergyEgg: true,
      isAllergyMilk: false,
      isAllergyCheese: true,
      isAllergyFish: false,
      isAllergyShellFish: false,
      isFiftyBelow: false,
      price: "167.00",
      isFiftyToOneHundred: false,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: true,
      isTwoHundredAbove: false),
  Meal(
      id: 'm17',
      categories: ['c1', 'c3', 'c4'],
      title: 'Belgian Waffle',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/Belgian_Waffle.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/belgian_waffle.glb?raw=true',
      details: 'Waffle, chocolate, Strawberry, blackberries',
      sauce: '',
      scale: 0.1,
      isHalal: true,
      isKeto: true,
      isSeaFood: false,
      isDessert: false,
      isVegan: true,
      isAllergyEgg: false,
      isAllergyMilk: false,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "225.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: false,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: true),
  Meal(
      id: 'm18',
      categories: ['c1', 'c3', 'c4'],
      title: 'Ravioli',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/ravioli.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/ravioli.glb?raw=true',
      details:
          'flour, eggs, salt, ricota cheese, shredded part-skim mozzarella cheese, Parmesan cheese, fresh basil, fresh parsley, fresh oregano, garlic powder, pepper',
      sauce:
          'crushed tomatoes, tomato puree, parmesan cheese, water, tomato paste, sugar, minced fresh basil, oregano and parsley.',
      scale: 0.1,
      isHalal: true,
      isKeto: true,
      isSeaFood: false,
      isDessert: false,
      isVegan: true,
      isAllergyEgg: true,
      isAllergyMilk: false,
      isAllergyCheese: true,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "145.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: false,
      isOneHundredToOneFifty: true,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: false),
  Meal(
      id: 'm19',
      categories: ['c1', 'c3', 'c4'],
      title: 'Capuccino',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/capuccino.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/capuccino.glb?raw=true',
      details: 'finely ground dark roast coffee, water, milk, marshmallow',
      sauce: '',
      scale: 1.0,
      isHalal: true,
      isKeto: true,
      isSeaFood: false,
      isDessert: false,
      isVegan: true,
      isAllergyEgg: false,
      isAllergyMilk: true,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "80.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: true,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: false),
  Meal(
      id: 'm20',
      categories: ['c1', 'c3', 'c4'],
      title: 'Salmonroe Sushi',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/salmonroe_sushi.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/salmonroe_sushi.glb?raw=true',
      details: 'finely ground dark roast coffee, water, milk, marshmallow',
      sauce: '',
      scale: 0.1,
      isHalal: true,
      isKeto: true,
      isSeaFood: false,
      isDessert: false,
      isVegan: true,
      isAllergyEgg: false,
      isAllergyMilk: true,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "135.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: false,
      isOneHundredToOneFifty: true,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: false),
  Meal(
      id: 'm21',
      categories: ['c1', 'c3', 'c4'],
      title: 'Red Velvet Cake',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/red_velvet_cake.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/red_velvet_cake.glb?raw=true',
      details:
          'shortening, white sugar, eggs, cocoa, red food coloring, salt, vanilla extract, buttermilk, all-purpose flour, baking soda, distilled white vinegar, milk, butter, ',
      sauce: '',
      scale: 1.0,
      isHalal: true,
      isKeto: true,
      isSeaFood: false,
      isDessert: false,
      isVegan: true,
      isAllergyEgg: false,
      isAllergyMilk: false,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "225.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: false,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: true),
  Meal(
      id: 'm22',
      categories: ['c1', 'c3', 'c4'],
      title: 'Donuts',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/donuts.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/donuts.glb?raw=true',
      details:
          'flour, sugar, eggs, butter, powdered sugar, bakers yeast, baking powder, chocoloate glaze, strabery glaze, sprinkles',
      sauce: '',
      scale: 0.1,
      isHalal: true,
      isKeto: true,
      isSeaFood: false,
      isDessert: false,
      isVegan: true,
      isAllergyEgg: false,
      isAllergyMilk: false,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "35.00",
      isFiftyBelow: true,
      isFiftyToOneHundred: false,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: false),
  Meal(
      id: 'm23',
      categories: ['c1', 'c3', 'c4'],
      title: 'Spicy Ramen',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/spicy_Ramen.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/spicy_Ramen.glb?raw=true',
      details:
          'beef shank, ramen noodles, soy sauce, garlic, shallots, ginger, chili  pepper, green onion, sugar, beef stocked powder, cooking oil, water, blackpepper, chili flakes',
      sauce: '',
      scale: 0.1,
      isHalal: true,
      isKeto: true,
      isSeaFood: false,
      isDessert: false,
      isVegan: false,
      isAllergyEgg: false,
      isAllergyMilk: false,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "76.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: true,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: false),
  Meal(
      id: 'm24',
      categories: ['c1', 'c3', 'c4'],
      title: 'Fruit Cream Cake',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/fruit_cream_cake.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/fruit_cream_cake.glb?raw=true',
      details:
          "2 and 1/2 cups (285g) cake flour, 2 teaspoons baking powder, 1/2 teaspoon baking soda, 1 teaspoon salt, 3/4 cup (1.5 sticks; 170g) unsalted butter, softened to room temperature , 1 and 3/4 cups (350g) granulated sugar, 5 large egg whites, at room temperature, 1/2 cup (120g) sour cream, at room temperature*, 1 Tablespoon pure vanilla extract (yes, Tbsp!), 1 cup (240ml) whole milk, at room temperature*",
      sauce: '',
      scale: 0.1,
      isHalal: false,
      isKeto: false,
      isSeaFood: false,
      isDessert: true,
      isVegan: false,
      isAllergyEgg: true,
      isAllergyMilk: true,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "124.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: false,
      isOneHundredToOneFifty: true,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: false),
  Meal(
      id: 'm245',
      categories: ['c1', 'c3', 'c4'],
      title: 'Cherry Pie',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/cherrypie.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/cherrypie.glb?raw=true',
      details:
          "4 cups fresh or frozen tart cherries, 1 to 1 ½ cups granulated sugar, 4 tablespoon cornstarch, 1/8 tablespoon almond extract (optional), Your favorite pie crust or pie dough recipe for 2 crust pie, 1 ½ tablespoon butter, to dot, 1 tablespoon granulated sugar, to sprinkle",
      sauce: '',
      scale: 0.1,
      isHalal: false,
      isKeto: false,
      isSeaFood: false,
      isDessert: true,
      isVegan: false,
      isAllergyEgg: true,
      isAllergyMilk: true,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "176.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: false,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: true,
      isTwoHundredAbove: false),
  Meal(
      id: 'm25',
      categories: ['c1', 'c3', 'c4'],
      title: 'Chocolate Cake',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/chococake.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/chococake.glb?raw=true',
      details:
          "1 3/4 cups all purpose flour, or (plain flour), (8 oz | 227 g), 3/4 cup unsweetened cocoa powder, (2.6 oz | 75 g) or regular Hershey's cocoa powder, 1 1/2 teaspoon baking powder, 1 1/2 teaspoon baking soda, (or bi-carb soda), 1 teaspoon salt, 2 cups white granulated sugar, (14 oz | 410 g), 2 large eggs, 1 cup milk, (250 ml), 1/2 cup vegetable oil, (125 ml),  2 teaspoons pure vanilla extract, 1 cup boiling water (250 ml)",
      sauce: '',
      scale: 0.1,
      isHalal: false,
      isKeto: false,
      isSeaFood: false,
      isDessert: true,
      isVegan: false,
      isAllergyEgg: true,
      isAllergyMilk: true,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "240.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: false,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: true),
  Meal(
      id: 'm26',
      categories: ['c1', 'c3', 'c4'],
      title: 'Cake With Cherry on Top',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/cake_with_cherry.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/cake_with_cherry.glb?raw=true',
      details:
          "3 large eggs, ½ cup oil, ¾ cup water, ¼ cup maraschino cherry juice, ½ teaspoon almond extract, 15.25-ounce box vanilla cake mix, 16 maraschino cherries, cut into quarters ",
      sauce: '',
      scale: 0.1,
      isHalal: false,
      isKeto: false,
      isSeaFood: false,
      isDessert: true,
      isVegan: false,
      isAllergyEgg: true,
      isAllergyMilk: false,
      isAllergyCheese: true,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "160.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: false,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: false,
      isTwoHundredAbove: true),
  Meal(
      id: 'm27',
      categories: ['c1', 'c3', 'c4'],
      title: 'Waffle With Honey',
      imageUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/wafflehoney.png?raw=true',
      threeDObjUrl:
          'https://github.com/agnieve70/3dObjects/blob/main/wafflehoney.glb?raw=true',
      details:
          "2 cups all-purpose flour, 1 ¾ cups milk, 2 eggs, 1/2 cup butter (melted), 1 tablespoon white sugar, 4 teaspoons baking powder, 1 teaspoon pure vanilla extract, 1/4 teaspoon salt ",
      sauce: '',
      scale: 0.1,
      isHalal: false,
      isKeto: false,
      isSeaFood: false,
      isDessert: true,
      isVegan: false,
      isAllergyEgg: false,
      isAllergyMilk: true,
      isAllergyCheese: false,
      isAllergyFish: false,
      isAllergyShellFish: false,
      price: "170.00",
      isFiftyBelow: false,
      isFiftyToOneHundred: false,
      isOneHundredToOneFifty: false,
      isOneFiftyToTwoHundred: true,
      isTwoHundredAbove: false),
];
